name: ScubedCap
favicon: null
layout_spectrum: 0.23151436215266585
typography_spectrum: 0.23546879994682967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#446adb'
    - '#45ae4e'
    - '#cf2730'
    - '#ffffff'
    - '#231f20'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
